name: CMKG
favicon: null
layout_spectrum: 0.23502
typography_spectrum: 0.65948
title: Category Management Knowledge Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e7e8'
    - '#7fb539'
    - '#034ea2'
    - '#f68b1f'
    - '#1d1d1d'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
