name: CMKG. Train Ahead.
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8605
title: Category Management Knowledge Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#414042'
    - '#5785ad'
    - '#636466'
    - '#72ace1'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
